#!/usr/bin/env bash
# Setup Solar EPC app to use self-hosted Supabase (Docker).
# Run from the Solar EPC project root: ./scripts/setup-selfhosted-supabase.sh
#
# 1. Runs DB migrations against the supabase-db container.
# 2. Writes .env.local with keys from supabase/docker/.env (if present).

set -e
cd "$(dirname "$0")/.."

echo "=== Solar EPC – Self-hosted Supabase setup ==="

# --- 1. Check Docker and supabase-db ---
if ! command -v docker &>/dev/null; then
  echo "Error: docker not found. Install Docker and try again."
  exit 1
fi

if ! docker ps --format '{{.Names}}' | grep -q 'supabase-db'; then
  echo "Error: Container 'supabase-db' not running. Start Supabase first:"
  echo "  cd supabase/docker && docker compose up -d"
  exit 1
fi

echo "Found supabase-db container."

# --- 2. Run migrations ---
echo ""
echo "Running migrations..."
docker exec -i supabase-db psql -U postgres -d postgres < db/migrations/00001_solar_epc_schema.sql
echo "  Done: 00001_solar_epc_schema.sql"
docker exec -i supabase-db psql -U postgres -d postgres < db/migrations/00002_rls_and_auth.sql
echo "  Done: 00002_rls_and_auth.sql"
docker exec -i supabase-db psql -U postgres -d postgres < db/migrations/00003_surveys_project_id.sql
echo "  Done: 00003_surveys_project_id.sql"
docker exec -i supabase-db psql -U postgres -d postgres < db/migrations/00004_surveys_optional_fields.sql
echo "  Done: 00004_surveys_optional_fields.sql"
docker exec -i supabase-db psql -U postgres -d postgres < db/migrations/00005_survey_uploads_bucket.sql
echo "  Done: 00005_survey_uploads_bucket.sql"
docker exec -i supabase-db psql -U postgres -d postgres < db/migrations/00006_anon_rls_app_tables.sql
echo "  Done: 00006_anon_rls_app_tables.sql"
docker exec -i supabase-db psql -U postgres -d postgres < db/migrations/00007_anon_storage_policies.sql
echo "  Done: 00007_anon_storage_policies.sql"
echo "Migrations complete."

# --- 3. .env.local from supabase/docker/.env ---
DOCKER_ENV="supabase/docker/.env"
if [ -f "$DOCKER_ENV" ]; then
  echo ""
  echo "Reading keys from $DOCKER_ENV ..."
  # Extract values (handle optional quotes)
  ANON_KEY=$(grep -E '^ANON_KEY=' "$DOCKER_ENV" | sed 's/^ANON_KEY=//' | tr -d '"' | tr -d "'" || true)
  SERVICE_ROLE_KEY=$(grep -E '^SERVICE_ROLE_KEY=' "$DOCKER_ENV" | sed 's/^SERVICE_ROLE_KEY=//' | tr -d '"' | tr -d "'" || true)
  API_URL=$(grep -E '^API_EXTERNAL_URL=' "$DOCKER_ENV" | sed 's/^API_EXTERNAL_URL=//' | tr -d '"' | tr -d "'" || true)
  KONG_HTTP_PORT=$(grep -E '^KONG_HTTP_PORT=' "$DOCKER_ENV" | sed 's/^KONG_HTTP_PORT=//' | tr -d '"' | tr -d "'" || true)
  [ -z "$KONG_HTTP_PORT" ] && KONG_HTTP_PORT=8000

  if [ -n "$ANON_KEY" ] && [ -n "$SERVICE_ROLE_KEY" ]; then
    [ -z "$API_URL" ] && API_URL="http://localhost:${KONG_HTTP_PORT}"
    cat > .env.local << EOF
# Generated by scripts/setup-selfhosted-supabase.sh – Solar EPC + self-hosted Supabase
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
EOF
    echo "Wrote .env.local with NEXT_PUBLIC_SUPABASE_URL, ANON_KEY, and SERVICE_ROLE_KEY."
  else
    echo "Could not find ANON_KEY or SERVICE_ROLE_KEY in $DOCKER_ENV."
    echo "Manually copy from supabase/docker/.env into .env.local (see .env.example)."
  fi
else
  echo ""
  echo "No $DOCKER_ENV found. To get keys:"
  echo "  1. From the directory where you ran 'docker compose up -d' (e.g. supabase/docker), open .env"
  echo "  2. Copy ANON_KEY → NEXT_PUBLIC_SUPABASE_ANON_KEY, SERVICE_ROLE_KEY → SUPABASE_SERVICE_ROLE_KEY"
  echo "  3. Set NEXT_PUBLIC_SUPABASE_URL=http://localhost:<KONG_HTTP_PORT> (often 8000; check supabase/docker/.env)"
  echo "  4. Put them in this project's .env.local"
fi

echo ""
echo "=== Next steps ==="
echo "  1. Ensure .env.local has NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY (and optionally SUPABASE_SERVICE_ROLE_KEY)."
echo "  2. Run: npm run dev"
echo "  3. Run the app on port 3001 (Studio uses 3000): npm run dev -- -p 3001"
echo "  4. Open http://localhost:3001 → Sign up. Then in Studio (http://localhost:3000) set your profile role to 'admin' in Table Editor → profiles."
echo "Done."
